### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by adrpan** [TheDevFab/TradingView-Webhook-Bot#10]
Hi, after long hours work time, sometimes week, or two i getting this message "Can't parse entities: can't find end of the entity starting at byte offset 161"

I dont know why showig date 2020-10-14 when that was send 3-4 days ago
Here last log: 

```
[OK!] 2020-10-14 00:16:03 Alert Received & Sent!
> BTC/USDT TF H1
SHORT Sell,
Entry: 13512.240789195805,
Take profits: TP1: 13310.60445 TP2: 13176.1539, TP3: 13041.70335
Stop Loss: null
[OK!] 2020-10-14 00:16:03 Alert Received & Sent!
> BTC/USDT TF H1
LONG Buy
Entry: 13292.075942768162,
Take profits: TP1: 13432.058175000002 TP2: 13565.048850000001, TP3: 13698.039525000002
Stop Loss: null
[OK!] 2020-10-14 00:16:03 Alert Received & Sent!
> BTCUSDT SHORT Sell
Binance Futures, Bybit
Entry: {{OpenS}}
Take profits:
TP1: 13310.60445
TP2: 13176.1539
TP3: 13041.70335
TP4: 12907.2528
TP5: 12772.802249999999
Stop Loss: {SLi_short)}}
Can't parse entities: can't find end of the entity starting at byte offset 178
[OK!] 2020-10-14 00:16:03 Alert Received & Sent!
> LONG Buy, Binance Futures, Bybit. Entry: 13492.592658598704, Take profits: TP1: 13643.5849999091 TP2: 13778.669999908201, TP3: 13913.7549999073 Stop Loss: {{("SL_long)"}}
Can't parse entities: can't find end of the entity starting at byte offset 161
[OK!] 2020-10-14 00:16:03 Alert Received & Sent!
> LONG Buy, Binance Futures, Bybit. Entry: 13480.750247856926, Take profits: TP1: 13646.808922535101 TP2: 13781.9258425602, TP3: 13917.0427625853 Stop Loss: {{("SL_long)"}}
Can't parse entities: can't find end of the entity starting at byte offset 161
Can't parse entities: can't find end of the entity starting at byte offset 161
```
> BTCUSDT Crossing 13522.0000000
[OK!] 2020-10-31 07:27:05 Alert Received & Sent!
> ETHUSDT LONG Buy
Binance Futures, Bybit
Entry: 383.2277615040855
Take profits:
TP1: 382.56034375
TP2: 386.9270374999999
TP3: 390.15459375
TP4: 393.95171875
TP5: 397.74884375
Stop Loss: {{("SL_LONG")}}
Can't parse entities: can't find end of the entity starting at byte offset 192
[OK!] 2020-10-31 07:27:05 Alert Received & Sent!
> BTCUSDT LONG Buy
Binance Futures, Bybit
Entry: 13519.210206668417
Take profits:
TP1: 13432.058175000002
TP2: 13565.048850000001
TP3: 13698.039525000002
TP4: {{plot("LongTP4")}}
TP5: {{plot("LongTP5")}}
Stop Loss: {{("SL_LONG")}}
Can't parse entities: can't find end of the entity starting at byte offset 220

**Comment by TheDevFab** [comment]
Hi, 

My first question would be, did it ever work for you? Secondly it seems `{{("SL_LONG")}}` is not being transmitted correctly. You may want to look into that.

In terms of your time, it simply takes your server time. That might've been set incorrectly. Do you run it on a VPS?

**Comment by adrpan** [comment]
Generally yes it works, but in this time i changed some things in indicator code, and now has been fixed. Im using dedicated server, and date is correct, coz other things work with correct date.

> Hi,
> 
> My first question would be, did it ever work for you? Secondly it seems `{{("SL_LONG")}}` is not being transmitted correctly. You may want to look into that.
> 
> In terms of your time, it simply takes your server time. That might've been set incorrectly. Do you run it on a VPS?

**Comment by TheDevFab** [comment]
Glad to hear that it is working now. The log entry uses `timestamp` which refers to your local server time. Unsure why yours are off if it's set correctly.
