### ISSUE TITLE
Custom Telegram Message

### ISSUE THREAD

**Issue by alipoursanati** [TheDevFab/TradingView-Webhook-Bot#3]
Dear Fabian Spranger, 
First of all, I appreciate your great project. I have a problem and I will appreciate it if you help me to solve that. I want to customize the alert message before being sent to telegram, for instance, adding custom price based on {{close}} price, but I cannot find out how to do that.
Thank you in advance.

**Comment by TheDevFab** [comment]
Hi @alipoursanati,

Sorry for the late response. Just a little busy these days. I'll try to help you with a more in depth reply layer this week.

**Comment by TheDevFab** [comment]
Hi again,

To add custom price data you'd most likely have to implement an extra layer of API's from either exchanges directly or using data from [CoinMarketCap](https://coinmarketcap.com/api/), [CoinGecko](https://www.coingecko.com/en/api), etc.

Next you'd have to edit [`handler.py`](https://github.com/TheDevFab/TradingView-Webhook-Bot/blob/master/handler.py) and implement it there. Hope that helps a bit. In case you need more assistance let me know!

**Comment by TheDevFab** [comment]
I'll close this issue now. Let me know if anything is still unclear.
