### ISSUE TITLE
ImportError: cannot import name 'Bot' from 'telegram'

### ISSUE THREAD

**Issue by ajmal017** [TheDevFab/TradingView-Webhook-Bot#5]
ImportError                               Traceback (most recent call last)
<ipython-input-11-6461afbbd77e> in <module>
      6 from email.mime.text import MIMEText
----> 7 from telegram import Bot
      8 import logging
      9 import traceback

ImportError: cannot import name 'Bot' from 'telegram' (/root/anaconda3/lib/python3.8/site-packages/telegram/__init__.py)

**Comment by TheDevFab** [comment]
Hi, do you run `main.py` inside your virtual environment?

The Telegram framework should've been installed with `pip install -r requirements.txt`.

To confirm, that please type `pip list` and paste the output here. Thank you.

**Comment by TheDevFab** [comment]
Please be sure to run the application in a virtual environment, as mentioned in the [readme](https://github.com/TheDevFab/TradingView-Webhook-Bot#installation), so there wont be such complication. 

To create a venv issue `python3 -m venv <FOLDER>`. To enable it issue `source <FOLDER>/bin/activate`.
