### ISSUE TITLE
My session closes after I close the SSH terminal. Please help

### ISSUE THREAD

**Issue by nikhilphoto** [TheDevFab/TradingView-Webhook-Bot#6]
Hey TheDevFab

First of All. Big Thumps up for such an awesome script. When I found this I knew this is gold for learners like me.

I have been testing and tweaking with your script with my limited knowledge. I was able to set up the bot. But I connect to my terminal using Bitvise. I run my script but when I close my terminal the script stops running and no signals get generated. Please help me resolve this!

Regards,
Your script lover!

**Comment by TheDevFab** [comment]
Hi nikhilphoto,

Thanks for the kind words. If you'd like to run the script in the background I can either recommend [systemd](https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd) or [PM2](https://pm2.keymetrics.io/). Let me know if you have issues setting it up.

**Comment by nikhilphoto** [comment]
Thanks for the quick response
I really appreciate it.
For now I am using tmux to keep my session running. It went well there.

I wish to know if you have any bot trading related developments also
happening?

For example I wish to use the signals I am getting from Trading to not only
send to telegram but to also automate bot trading using those signals on
Binance.com

Let me know if you can point me in the right direction. Also let me know if
you would be interested in building such a script.
We can discuss pricing as well.

Thanks and Regards,
Nikhil Kumar
#9953166684

**Comment by TheDevFab** [comment]
I build a similar bot for myself but its not open source. If you'd like to build something yourself I can recommend to take a look at [ccxt](https://ccxt.trade).

**Comment by Dirtbikes1** [comment]
Can you elaborate on how to get this to run on reboot? I was using a Ubuntu server, but now I have it working on a Ubuntu desktop but would like it to run if the system has to reboot for some reason. It seems systemd would be the best choice just not sure how to go about this. Thanks.
