### ISSUE TITLE
Security where are you?

### ISSUE THREAD

**Issue by jon4hz** [TheDevFab/TradingView-Webhook-Bot#7]
Hi, first of all very cool code, gonna steal that for my project :P 
But I have some concerns about security. Wouldn't it be better to send a code (like a password) within the signal from tradingview? To ensure that the signal is coming from there? Otherwise everyone who knows you IP could send fake signals and wreck your portfolio. Gonna send you the code if I find the time to implement it :)

**Comment by TheDevFab** [comment]
Yep, if your concerned of such things it may be good to implement. Shouldn't take much to add that. If your doing it a pull request would be appreciated.
